[package]
name = "page_loader"
version = "0.1.0"
authors = ["Daniel Bunte <daniel.bunte.84@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# internal
tarantula_core = { path = "../core" }
dom_parser = { path = "../dom_parser" }
linkresult = { path = "../linkresult" }
# external
chrono = "0.4.19"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
log = "0.4.14"
log4rs = "1.0.0"
num_cpus = "1.13.0"
tokio = { version = "^1", features = ["full"] }

[dev-dependencies]
faux = "^0.1"
mockall = "0.9.1"
mockall_double = "0.2.0"