[package]
name = "page_loader"
version = "0.1.0"
authors = ["Daniel Bunte <daniel.bunte.84@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
log = "0.4.14"
log4rs = "1.0.0"
num_cpus = "1.13.0"
tokio = { version = "1", features = ["full"] }