stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


build_latest:
  stage: build
  image: 'rust:latest'
  script:
    - rustup default nightly
    - cargo test --workspace
    - cargo build --release
  artifacts:
    paths:
      - tarantula

deploy_latest:
  stage: build
  image: 'rust:latest'
  script:
    - rustup default nightly
    - cargo test --workspace
    - cargo build --release
    - rm -rf tarantula 2> /dev/null
    - mkdir tarantula
    - mv deploy.sh tarantula/deploy.sh
    - mv target/release/tarantula tarantula/
    - scp -r tarantula tarantula@tarantula.versionmanager.io:~
    - ssh tarantula@tarantula.versionmanager.io 'cd tarantula; ./deploy.sh'
  artifacts:
    paths:
      - tarantula
  only:
    - main

cache:
  paths:
    - apt/
    - cargo/
    - target/
