[package]
name = "tarantula"
version = "0.1.0"
authors = ["Daniel Bunte (@DuncanConroy) <daniel.bunte.84+github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "dom_parser",
    "linkresult",
]

[dependencies]
# internal
dom_parser = { path = "dom_parser" }
# external
futures = "0.3.12"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
tokio = { version = "1", features = ["full"] }
pretty_env_logger = "0.4"
robotparser = "0.10.2"