[package]
name = "tarantula"
version = "0.1.0"
authors = ["Daniel Bunte (@DuncanConroy) <daniel.bunte.84+github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "dom_parser",
    "linkresult",
    "page_loader",
]

[dependencies]
# internal
core = { path = "core" }
# external
clap = { version = "2.33", features = ["yaml"] }
num_cpus = "1.13.0"
log = "0.4.14"
log4rs = "1.0.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
testutils = { path = "testutils" }