[package]
name = "linkresult"
version = "0.1.0"
authors = ["Daniel Bunte (@DuncanConroy) <daniel.bunte.84+github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
fancy-regex = "0.4.1"
hyper = { version = "0.14", features = ["full"] }
rand = "0.8.3"
scraper = "0.12.0"
