@startuml
package page_loader {
    class HTMLResult
    class LinkTag {
        +enclosing_html_tag(): String|Tag|HTML
        +link(): Link
    }
    class PageLoader{
    PageLoader:fetch_head()
        fetch_head(gets head result, then fetches page)
    }
}

@enduml

Redirects muessen mitgespeichert werden
LoadPageCommand -> original url request
 -> redirected List
